### ISSUE TITLE
Pipeline assignment?

### ISSUE THREAD

**Issue by DiriectorDoc** [tc39/proposal-pipeline-operator#194] opened 2021-09-02 05:10 UTC
The only thing that came to mind was this:

```javascript
let val = 2.5;

val |>= Math.round;
```

To be honest, I never saw much use for the raw pipeline (`|>`) because, in my eyes, it's the same as just using parentheses. But pipeline assignments could actually make things easier.

**Comment by tabatkins** [comment] 2021-09-08 23:38
Closing as a dupe of #125

**Closed by tabatkins** 2021-09-08 23:38 UTC
Labels: enhancement
