### ISSUE TITLE
Functions with multiple arguments

### ISSUE THREAD

**Issue by fahad19** [tc39/proposal-pipeline-operator#59] opened 2017-09-28 16:22 UTC
## Currently

The spec suggests function with multiple arguments be used like this:

Base functions:

```js
function double(x) {
  return x * 2;
}

function add(x, y) {
  return x + y;
}
```

Pipe operator usage:

```js
const score = 10;

const newScore = score
  |> double
  |> _ => add(7, _)

console.log(newScore); // 27;
```

## Proposed change

Instead of writing extra function wrappers for passing arguments, the operator can always make sure the output from previous function as fed as the first argument of next function.

```js
const newScore = score
  |> double // output of `score` is first argument: `double(10)`
  |> add(7) // output of `double(10)` is first argument: `add(10, 7)`

console.log(newScore); // 27
```

This is how Elixir works: https://hexdocs.pm/elixir/Kernel.html#%7C%3E/2

---

If TC39 is interested in this, I am happy to send a PR for improving this spec further.

**Comment by gilbert** [comment] 2017-09-28 16:29
Closing as a subset duplicate of #55

**Closed by gilbert** 2017-09-28 16:29 UTC
