### ISSUE TITLE
Composition operator

### ISSUE THREAD

**Issue by zhaoyao91** [tc39/proposal-pipeline-operator#54] opened 2017-08-28 02:32 UTC
Pipeline operator is good, but I thinks **composition operator** is more expected by the functional paradigm.

Suppose we define * as the composition operator, then 
```
f(g(h(x))) 
```
could be written as
```
 f*g*h*x
```
Further more, an [issue](https://github.com/tc39/proposal-decorators/issues/35) of proposal-decorators and react could be solved gracefully by this operator.

e.g. for react hoc composition:

```
const Comp = compose(
  hoc1,
  hoc2,
  ...
)((props) => <div>...</div>)
```

it could be written as:

```
const Comp =
ho1*
hoc2*
hoc3*
...
(props) => <div>...</div>
```

**Comment by TehShrike** [comment] 2017-08-28 02:40
Duplicate of #50.

Function composition should be proposed in its own proposal.

**Closed by TehShrike** 2017-08-28 02:40 UTC
