### ISSUE TITLE
Shouldn't it just be a composition operator?

### ISSUE THREAD

**Issue by devlato** [tc39/proposal-pipeline-operator#103] opened 2018-03-11 21:44 UTC
Hello,

what's the purpose of this operator? Shouldn't it just be a function composition operator that returns a new composed function?

**Comment by gilbert** [comment] 2018-03-11 23:47
Duplicate of https://github.com/tc39/proposal-pipeline-operator/issues/50

**Closed by gilbert** 2018-03-11 23:47 UTC
